name: Go

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: |
          go test -v